In [5]:
import numpy as np
np.random.rand()

0.6178462096638282

In [6]:
np.random.rand(10)

array([0.35966473, 0.00919566, 0.66052442, 0.30163996, 0.79587565,
       0.8494795 , 0.11968118, 0.8262297 , 0.11681486, 0.59046489])

In [8]:
np.random.rand(5,2).reshape(2,1,5)

array([[[0.24567442, 0.76410509, 0.74701089, 0.00358179, 0.33218159]],

       [[0.57888198, 0.7985553 , 0.55559956, 0.54626542, 0.91206286]]])

In [9]:
np.random.randn()

0.43506600447509425

In [11]:
np.random.randn(3, 3)

array([[-0.03395783,  1.28872752,  0.33792273],
       [-0.77574061, -0.29725653, -0.81448721],
       [ 0.04518616,  0.29096888,  0.85532587]])

In [13]:
np.random.randint(1,100)

68

In [21]:
np.random.randint(1,100,5)

array([83,  1, 37, 31, 87])

In [30]:
r,g,b=np.random.randint(0,255,3)
print(r,g,b)

46 93 146


In [34]:
res3=np.random.choice([90,100,110],p=[0.3,0.6,0.1],size=(3,10))
print(res3)

[[ 90  90  90 100 100 100 100 100  90 100]
 [100 100 100 100  90  90 100 100 100  90]
 [110 100 100  90  90 100 100 100 100  90]]


In [36]:
#FILTERING METHOD
arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [37]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [38]:
np.where(arr<100)

(array([0, 1, 3, 5, 6], dtype=int64),)

In [39]:
arr[np.where(arr<100)]

array([ 1,  2,  4, 18, 71])

In [41]:
#or directly you can use
arr[arr>100]

array([1010,  108,  610])

In [42]:
arr[arr%2==0]

array([   2, 1010,    4,  108,   18,  610])

In [48]:
arr[(arr%2!=0) & (arr>50)]

array([71])

In [ ]:
#FANCY INDEXING SELF-STUDY CONCEPT (LMS PORTAL)